### ISSUE TITLE
Fail to clone from OpenMBEE Git repository

### ISSUE THREAD

**Issue by William1003** [Open-MBEE/Comodo#6]
When I try to clone the project using `git clone https://github.com/Open-MBEE/Comodo.git comodo2`
It shows:
 **Error downloading object: libs/ST-4.3.1.jar (ebc9d9b): Smudge error: Error downloading lib
s/ST-4.3.1.jar (ebc9d9bcdb67571c0835ff441ead5c1de90a25a0d3fa840654a144e8fa0410d4): batch r
esponse: This repository is over its data quota. Account responsible for LFS bandwidth sho
uld purchase more data packs to restore access.**
I think that it may be something wrong with the repository. I will appreciate it if you could help to fix it...!

**Comment by landolfa** [comment]
One (obvious) solution is to increase the disk quota.

Another one is to change the build system and avoid archiving the jar libraries. This may take quite some time and effort.

By the way, was anybody notified by GitHub about the exceeded quota? I wasn't.

**Comment by wobrschalek** [comment]
@William1003 please see also the slack conversation
https://openmbee.slack.com/archives/C01FFLQAEUQ/p1666979127664219

**Comment by wobrschalek** [comment]
we should introduce dependency management and get the jar files from maven central like we do for MMS.
e.g. https://github.com/Open-MBEE/mmsri/blob/develop/build.gradle
is that something you could take on @William1003 ?

**Comment by wobrschalek** [comment]
for instance, that ST-4.3.1.jar should be pulled from here
https://mvnrepository.com/artifact/org.antlr/ST4/4.3.1
not versioned in the repository

**Comment by William1003** [comment]
> we should introduce dependency management and get the jar files from maven central like we do for MMS. e.g. https://github.com/Open-MBEE/mmsri/blob/develop/build.gradle is that something you could take on @William1003 ?

Thanks a lot! I will try it and I think it would work.

**Comment by thomas-bc** [comment]
This issue was closed but I still get the error message when cloning the repository. Are there any workarounds?

**Comment by landolfa** [comment]
Hi @William1003,
any progress in porting COMODO to gradle or maven?

**Comment by landolfa** [comment]
A temporary workaround is to wait the beginning of the month so that GitHub LFS bandwidth quota is reset to 0 (see https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage).
